// Code generated by sqlc. DO NOT EDIT.
// This file mirrors what sqlc would generate for the accounts and sessions tables.
// Run `make generate` to regenerate from queries.sql.
package dbsqlc

import "time"

type Account struct {
	ID             string    `json:"id"`
	GithubID       int64     `json:"github_id"`
	GithubUsername string    `json:"github_username"`
	DisplayName    string    `json:"display_name"`
	AvatarUrl      string    `json:"avatar_url"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Session struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}
