// Code generated by sqlc. DO NOT EDIT.
// This file mirrors what sqlc would generate from queries.sql.
// Run `make generate` to regenerate.
package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

// Querier provides type-safe access to database queries.
type Querier struct {
	db *sql.DB
}

// New returns a new Querier backed by the given database connection.
func New(db *sql.DB) *Querier {
	return &Querier{db: db}
}

// GetAccountByGitHubID looks up an account by its GitHub numeric ID.
func (q *Querier) GetAccountByGitHubID(ctx context.Context, githubID int64) (*Account, error) {
	const query = `SELECT id, github_id, github_username, display_name, avatar_url, role, created_at, updated_at
FROM accounts WHERE github_id = ? LIMIT 1`
	row := q.db.QueryRowContext(ctx, query, githubID)
	return scanAccount(row)
}

// GetAccountByID looks up an account by its UUID primary key.
func (q *Querier) GetAccountByID(ctx context.Context, id string) (*Account, error) {
	const query = `SELECT id, github_id, github_username, display_name, avatar_url, role, created_at, updated_at
FROM accounts WHERE id = ? LIMIT 1`
	row := q.db.QueryRowContext(ctx, query, id)
	return scanAccount(row)
}

// GetAccountByUsername looks up an account by GitHub username.
func (q *Querier) GetAccountByUsername(ctx context.Context, username string) (*Account, error) {
	const query = `SELECT id, github_id, github_username, display_name, avatar_url, role, created_at, updated_at
FROM accounts WHERE github_username = ? LIMIT 1`
	row := q.db.QueryRowContext(ctx, query, username)
	return scanAccount(row)
}

// CreateAccountParams holds parameters for CreateAccount.
type CreateAccountParams struct {
	ID             string
	GithubID       int64
	GithubUsername string
	DisplayName    string
	AvatarUrl      string
	Role           string
}

// CreateAccount inserts a new account row and returns the created account.
func (q *Querier) CreateAccount(ctx context.Context, arg CreateAccountParams) (*Account, error) {
	const query = `INSERT INTO accounts (id, github_id, github_username, display_name, avatar_url, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
RETURNING id, github_id, github_username, display_name, avatar_url, role, created_at, updated_at`
	row := q.db.QueryRowContext(ctx, query,
		arg.ID, arg.GithubID, arg.GithubUsername, arg.DisplayName, arg.AvatarUrl, arg.Role)
	return scanAccount(row)
}

// UpdateAccountParams holds parameters for UpdateAccount.
type UpdateAccountParams struct {
	ID             string
	GithubUsername string
	DisplayName    string
	AvatarUrl      string
}

// UpdateAccount updates mutable fields on an account and returns the updated row.
func (q *Querier) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (*Account, error) {
	const query = `UPDATE accounts SET github_username = ?, display_name = ?, avatar_url = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, github_id, github_username, display_name, avatar_url, role, created_at, updated_at`
	row := q.db.QueryRowContext(ctx, query, arg.GithubUsername, arg.DisplayName, arg.AvatarUrl, arg.ID)
	return scanAccount(row)
}

// CreateSessionParams holds parameters for CreateSession.
type CreateSessionParams struct {
	ID        string
	AccountID string
	TokenHash string
	ExpiresAt time.Time
}

// CreateSession inserts a new session row and returns it.
func (q *Querier) CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error) {
	const query = `INSERT INTO sessions (id, account_id, token_hash, expires_at, created_at)
VALUES (?, ?, ?, ?, datetime('now'))
RETURNING id, account_id, token_hash, expires_at, created_at`
	row := q.db.QueryRowContext(ctx, query, arg.ID, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	return scanSession(row)
}

// GetSessionByTokenHash looks up an active (non-expired) session by token hash.
func (q *Querier) GetSessionByTokenHash(ctx context.Context, tokenHash string) (*Session, error) {
	const query = `SELECT id, account_id, token_hash, expires_at, created_at
FROM sessions WHERE token_hash = ? AND expires_at > datetime('now') LIMIT 1`
	row := q.db.QueryRowContext(ctx, query, tokenHash)
	return scanSession(row)
}

// DeleteSession removes a session by its ID.
func (q *Querier) DeleteSession(ctx context.Context, id string) error {
	const query = `DELETE FROM sessions WHERE id = ?`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// DeleteExpiredSessions removes all sessions that have passed their expiry time.
func (q *Querier) DeleteExpiredSessions(ctx context.Context) error {
	const query = `DELETE FROM sessions WHERE expires_at <= datetime('now')`
	_, err := q.db.ExecContext(ctx, query)
	return err
}

// DeleteSessionsByAccountID removes all sessions for a given account (logout all).
func (q *Querier) DeleteSessionsByAccountID(ctx context.Context, accountID string) error {
	const query = `DELETE FROM sessions WHERE account_id = ?`
	_, err := q.db.ExecContext(ctx, query, accountID)
	return err
}

// ---------- scan helpers ----------

func scanAccount(row *sql.Row) (*Account, error) {
	a := &Account{}
	err := row.Scan(
		&a.ID, &a.GithubID, &a.GithubUsername, &a.DisplayName,
		&a.AvatarUrl, &a.Role, &a.CreatedAt, &a.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return a, nil
}

func scanSession(row *sql.Row) (*Session, error) {
	s := &Session{}
	err := row.Scan(&s.ID, &s.AccountID, &s.TokenHash, &s.ExpiresAt, &s.CreatedAt)
	if err != nil {
		return nil, err
	}
	return s, nil
}
